// GENERATED by packages/shared/scripts/generate-kotlin-contract.ts — do not edit.
package nl.taakhelden.core.api

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

@Serializable
public data class ApiErrorEnvelope(
    val error: Body,
) {
    @Serializable
    public data class Body(
        val code: String,
        val message: String,
    )
}

@Serializable
public data class ChildProfileDTO(
    val id: String,
    val displayName: String,
    val avatarId: String? = null,
    val ageMode: String,
)

@Serializable
public data class FamilyCodeResultDTO(
    val familyName: String,
    val children: List<ChildProfileDTO> = emptyList(),
)

@Serializable
public data class ChildSessionResultDTO(
    val accessToken: String,
    val refreshToken: String,
    val expiresIn: Int,
    val child: ChildProfileDTO,
)

@Serializable
public data class ParentSessionResultDTO(
    val userId: String,
    val familyId: String,
    val accessToken: String,
    val refreshToken: String,
    val expiresIn: Int,
)

@Serializable
public data class MemberViewDTO(
    val id: String,
    val role: String,
    val displayName: String,
    val avatarId: String? = null,
    val ageMode: String,
    val birthYear: Int? = null,
)

@Serializable
public data class ParentFamilyViewDTO(
    val viewer: String,
    val id: String,
    val name: String,
    val timezone: String,
    val inviteCode: String,
)

@Serializable
public data class InstanceViewDTO(
    val id: String,
    val taskId: String,
    val childId: String,
    val date: String,
    val status: String,
    val title: String,
    val icon: String? = null,
    val category: String,
    val points: Int,
    val photoBonusPoints: Int = 0,
    val approvalRequired: Boolean = false,
    val daypart: String? = null,
    val photoId: String? = null,
    val photoStatus: String? = null,
    val pointsEarned: Int? = null,
    val redoNote: String? = null,
    val completedAt: String? = null,
    val approvedAt: String? = null,
    val updatedAt: String? = null,
)

@Serializable
public data class TodayBalanceDTO(
    val childId: String,
    val balance: Int,
    val todayCompleted: Int,
    val todayTotal: Int,
    val weekProgress: Double,
    val streakDays: Int,
    val lifetimeEarned: Int,
)

@Serializable
public data class ChildTodayViewDTO(
    val viewer: String,
    val date: String,
    val instances: List<InstanceViewDTO> = emptyList(),
    val balance: TodayBalanceDTO,
)

@Serializable
public data class BadgeDTO(
    val id: String,
    val title: String,
    val icon: String,
)

@Serializable
public data class CompleteResultDTO(
    val pointsEarned: Int,
    val photoBonusPoints: Int = 0,
    val dayBonusEarned: Boolean = false,
    val weekBonusEarned: Boolean = false,
    val newBadges: List<BadgeDTO> = emptyList(),
    val newBalance: Int,
)

@Serializable
public data class ChildRewardViewDTO(
    val id: String,
    val title: String,
    val icon: String? = null,
    val price: Int,
    val limitPerWeek: Int? = null,
    val affordable: Boolean = false,
    val pinned: Boolean = false,
)

@Serializable
public data class SavingsGoalViewDTO(
    val rewardId: String,
    val title: String,
    val icon: String? = null,
    val price: Int,
    val progress: Double,
)

@Serializable
public data class ChildRewardsViewDTO(
    val viewer: String,
    val balance: Int,
    val rewards: List<ChildRewardViewDTO> = emptyList(),
    val savingsGoal: SavingsGoalViewDTO? = null,
)

@Serializable
public data class RedemptionViewDTO(
    val id: String,
    val rewardId: String,
    val title: String,
    val icon: String? = null,
    val price: Int,
    val childId: String,
    val status: String,
    val createdAt: String,
    val handledAt: String? = null,
)

@Serializable
public data class ChildRedemptionsViewDTO(
    val viewer: String,
    val redemptions: List<RedemptionViewDTO> = emptyList(),
)

@Serializable
public data class RedeemResultDTO(
    val redemptionId: String,
    val rewardId: String,
    val price: Int,
    val status: String,
    val newBalance: Int,
)

@Serializable
public data class SyncMutationDTO(
    val key: String,
    val op: String,
    val instanceId: String? = null,
    val rewardId: String? = null,
    val photoId: String? = null,
    val at: String? = null,
)

@Serializable
public data class SyncBodyDTO(
    val since: String? = null,
    val mutations: List<SyncMutationDTO> = emptyList(),
)

@Serializable
public data class SyncResultDTO(
    val key: String,
    val status: String,
    val points: Int? = null,
    val newBalance: Int? = null,
    val code: String? = null,
    val message: String? = null,
)

@Serializable
public data class SyncChangesDTO(
    val ledger: List<JsonObject> = emptyList(),
    val instances: List<InstanceViewDTO> = emptyList(),
    val rewards: List<ChildRewardViewDTO>? = null,
)

@Serializable
public data class SyncResponseDTO(
    val results: List<SyncResultDTO> = emptyList(),
    val changes: SyncChangesDTO,
    val serverTime: String,
)

@Serializable
public data class UploadIntentResponseDTO(
    val photoId: String,
    val uploadUrl: String,
)

@Serializable
public data class PhotoStatusResponseDTO(
    val photoId: String,
    val status: String,
    val url: String? = null,
)

@Serializable
public data class AvatarCatalogItemDTO(
    val id: String,
    val slot: String,
    val unlockType: String,
    val unlockThreshold: Int = 0,
    val unlockBadgeId: String? = null,
    val previewEmoji: String,
    val title: String,
    val sortOrder: Int = 0,
)

@Serializable
public data class AvatarCatalogResponseDTO(
    val items: List<AvatarCatalogItemDTO> = emptyList(),
)

@Serializable
public data class MemberAvatarEquippedDTO(
    val hat: String? = null,
    val background: String? = null,
    val accessory: String? = null,
)

@Serializable
public data class MemberAvatarStateDTO(
    val memberId: String,
    val equipped: MemberAvatarEquippedDTO = MemberAvatarEquippedDTO(),
    val unlocked: List<String> = emptyList(),
    val level: Int = 1,
    val lifetimeEarned: Int = 0,
)

@Serializable
public data class FamilyGoalDTO(
    val id: String,
    val title: String,
    val icon: String,
    val targetPoints: Int,
    val childIds: List<String> = emptyList(),
    val startedAt: String,
    val completedAt: String? = null,
    val status: String,
)

@Serializable
public data class FamilyGoalProgressDTO(
    val goalId: String,
    val title: String,
    val icon: String,
    val earnedPoints: Int,
    val targetPoints: Int,
    val status: String,
)

@Serializable
public data class FamilyGoalProgressResponseDTO(
    val progress: FamilyGoalProgressDTO? = null,
)

/** Proposal status mirrors `ProposalStatus` in packages/shared. */
@Serializable
public enum class ProposalStatus {
    @SerialName("pending")
    PENDING,

    @SerialName("approved")
    APPROVED,

    @SerialName("declined")
    DECLINED,
}

@Serializable
public data class TaskProposalDTO(
    val id: String,
    val childId: String,
    val title: String,
    val category: String,
    val icon: String = "star",
    val suggestedPoints: Int,
    val note: String? = null,
    val status: ProposalStatus = ProposalStatus.PENDING,
    val createdTaskId: String? = null,
    /**
     * WS-AI-GUARD (ADR-0006): server-set deterministic safety flag, parent-only.
     *
     * Absent rather than null for a child token — a child never learns that their own
     * text was flagged — so this must tolerate the key being missing entirely.
     */
    val reviewFlag: String? = null,
)

@Serializable
public data class TaskProposalListDTO(
    val proposals: List<TaskProposalDTO> = emptyList(),
)

/** Matches the WS-PAUSE `ChildPause` Zod schema in packages/shared. */
@Serializable
public data class ChildPauseDTO(
    val id: String,
    val childId: String,
    val startsOn: String,
    val endsOn: String? = null,
    val reason: String? = null,
    val active: Boolean = false,
)

@Serializable
public data class ChildPauseResponseDTO(
    val pauses: List<ChildPauseDTO> = emptyList(),
)

/** Response from `POST /rewards/{id}/pin` (not yet in the OpenAPI snapshot). */
@Serializable
public data class PinRewardResultDTO(
    val rewardId: String,
    val title: String,
    val price: Int,
    val progress: Double,
)

@Serializable
public data class ParentTodayChildDTO(
    val childId: String,
    val displayName: String,
    val avatarId: String? = null,
    val instances: List<InstanceViewDTO> = emptyList(),
    val balance: TodayBalanceDTO,
)

@Serializable
public data class ParentTodayViewDTO(
    val viewer: String,
    val date: String,
    val children: List<ParentTodayChildDTO> = emptyList(),
)

@Serializable
public data class ParentTaskManageDTO(
    val id: String,
    val title: String,
    val icon: String? = null,
    val points: Int,
    val assignees: List<String> = emptyList(),
)

@Serializable
public data class ParentRewardManageDTO(
    val id: String,
    val title: String,
    val icon: String? = null,
    val price: Int,
)

@Serializable
public data class ParentRewardsViewDTO(
    val viewer: String,
    val rewards: List<ParentRewardManageDTO> = emptyList(),
)

@Serializable
public data class WsTokenDTO(
    val token: String,
    val expiresIn: Int = 0,
)

@Serializable
public data class ExportJobDTO(
    val exportId: String,
    val status: String,
    val downloadUrl: String? = null,
)

@Serializable
public data class AccountDeleteResultDTO(
    val deletedAt: String,
    val purgeAfter: String,
)
